FROM node:9 as builder

# Create app directory
RUN mkdir -p /var/www/lerna-fe
WORKDIR /var/www/lerna-fe

# Bundle app source
ADD . /var/www/lerna-fe

# Install dependencies
RUN npm install --quiet
RUN npm run build

# Copy built app into nginx container
FROM nginx:1.16.0-alpine
COPY --from=builder /var/www/lerna-fe/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]