version: "3"

services:
  lerna_db:
    container_name: lerna_db
    hostname: lerna_db
    image: mysql:5.7
    volumes:
      - lerna_db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${TYPEORM_DATABASE}
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
      - MYSQL_USER=${TYPEORM_USERNAME}
    ports:
      - "3306"
  lerna_client:
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://lerna.space/api
    container_name: lerna_client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - build_volume:/var/www/lerna-fe/build
  lerna_api:
    environment:
      - NODE_ENV=production
    container_name: lerna_api
    build: ./server
    ports:
      - "3000"
    depends_on:
      - lerna_db
  ngnix:
    build:
      context: ./media
      dockerfile: Dockerfile.prod
    ports:
      - "1935:1935"
      - "80:80"
      - "443:443"
    volumes:
      - ./media/data/rec:/opt/data/rec
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - build_volume:/var/www/lerna-fe/build
    depends_on:
      - lerna_api
      - lerna_db
      - lerna_client
    links:
      - lerna_api
      - lerna_client
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - lerna_db:db
    ports:
      - 8765:80
    environment:
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
    depends_on:
      - lerna_db
volumes:
  lerna_db_data:
  build_volume:
