version: "3"

services:
  lerna_db:
    container_name: lerna_db
    hostname: lerna_db
    image: mysql:5.7
    volumes:
      - lerna_db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${TYPEORM_DATABASE}
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
      - MYSQL_USER=${TYPEORM_USERNAME}
    ports:
      - "3306:3306"
  lerna_client:
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:3000
    container_name: lerna_client
    build: ./client
    volumes:
      - ./client/src:/var/www/lerna-fe/src
      - ./client/node_modules
    ports:
      - "3001:3001"
  lerna_api:
    environment:
      - NODE_ENV=development
    container_name: lerna_api
    build: ./server
    volumes:
      - ./server/src:/var/www/lerna-be/src
    ports:
      - "3000:3000"
    depends_on:
      - lerna_db
  lerna_media:
    container_name: lerna_media
    build: ./media
    ports:
      - 1935:1935
      - 80:80
      - 8443:443
    volumes:
      - ./media/certs:/opt/certs
      - ./media/data/rec:/var/rec
    depends_on:
      - lerna_api
      - lerna_db
    links:
      - lerna_api
      - lerna_client
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - lerna_db:db
    ports:
      - 8765:80
    environment:
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
    depends_on:
      - lerna_db
volumes:
  lerna_db_data:
