version: 2.1
jobs:
  build-be:
    working_directory: ~/lerna-project/server
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:8-stretch
    steps:
      - checkout:
          path: ~/lerna-project
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - run:
      #     name: Unit Tests
      #     command: npm run test:cov
      # - run:
      #     name: Code Linting
      #     command: npm run lint
      # - run:
      #     name: Dist Build
      #     command: npm run build:dist
  build-fe:
    working_directory: ~/lerna-project/client
    docker:
      - image: circleci/node:8-stretch
    steps:
      - checkout:
          path: ~/lerna-project
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - run:
      #     name: Unit Tests
      #     command: npm run test:coverage
      # - run:
      #     name: Code Linting
      #     command: npm run lint
      - run:
          name: Dist Build
          command: npm run build
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $DROPLET_USER@$DROPLET_IP "cd ~/lerna-project/scripts && chmod +x ./deployer.sh && ./deployer.sh"     

workflows:
  version: 2
  build_fe_and_be:
    jobs:
      - build-be
      - build-fe:
          requires:
            - build-be
      - deploy:
          requires:
            - build-be
            - build-fe
          filters:
            branches:
              only: master
